### ISSUE TITLE
Active microrheology

### ISSUE THREAD

**Issue by Bradleydi** [rmari/LF_DEM#1]
Hi Rmari,

I found your codes are well-constructed and clear. I want to further add external force to particles but wonder how to calculate the stress from it. Do you have any suggestion?

Thanks!
Best
Bradley

**Comment by rmari** [comment]
Hi Bradley,

Sorry for answering so late. Thanks for your interest in our code!

You can calculate the stress as the first moment of the force field you apply:
![equation](http://latex.codecogs.com/gif.latex?%24%5CSigma%20%3D%20-%20V%5E%7B-1%7D%20%5Csum_i%20x_i%20F_%7Bext%7D%5Ei%24) 

Best,
Romain
